### ISSUE TITLE
Bug in example code

### ISSUE THREAD

**Issue by patseng** [coinapi/coinapi-sdk#19] opened 2018-01-24 22:27 UTC
When I run `python examples.py` I get a syntax error in coinapi_v1:

```
Traceback (most recent call last):
  File "examples.py", line 1, in <module>
    from coinapi_v1 import CoinAPIv1
  File "/coinapi-sdk/python-rest/coinapi_v1.py", line 196
    self.headers = {**self.DEFAULT_HEADERS, **headers, **header_apikey}
```

**Comment by broble1** [comment] 2018-02-22 02:00
Really is a shame they won't fix this.  My trading company revolves around python for development and data analysis with commodities and is looking for more crypto data. You would think they'd put some effort into their product.

**Comment by broble1** [comment] 2018-02-22 23:07
Anyone have a fix for this?

**Comment by Svisstack** [comment] 2018-02-23 23:50
I believe that it's not a bug, but just incompatibility with previous versions of Python. The example code was written for the 3.X version of python interpreter.

**Comment by broble1** [comment] 2018-02-25 22:05
Good call. I had been trying it with both 2 and 3 but I think that there was a issue with my installation of 3. Reinstalled 3 in a different main directory from 2 and it works now. Thanks for letting me know it was written for 3.

**Closed** 2018-04-13 13:34 UTC
Labels: bug, enhancement
